"""
reconciliation.py
=================
Information-reconciliation experiment library for the LDPC-vs-GRAND
comparison on BB84 sifted keys (see error_analysis.ipynb).

Both reconciliation methods are cast in the SAME syndrome-based protocol
so that leakage accounting is identical and the comparison is fair:

    1. Alice and Bob hold sifted keys x, y with y = x XOR e,
       where e is the error vector of a (approximately) BSC(p) channel.
    2. Alice computes s_A = H @ x (mod 2) and publishes it (m bits leaked).
    3. Bob computes s_delta = s_A XOR (H @ y) = H @ e (mod 2) and tries to
       find the most likely e consistent with that syndrome.
    4. Bob's corrected key is y XOR e_hat.

The two methods differ only in the code family and the search for e:

    LDPC  : sparse H from pyldpc.make_ldpc, syndrome-target sum-product
            belief propagation (the standard QKD reconciliation decoder).
    GRAND : dense random H, noise guessing - enumerate error patterns in
            increasing Hamming-weight order (ML for a BSC with p < 0.5)
            and accept the first pattern whose syndrome matches.

Leakage for both = m = number of syndrome rows published.

Key generation uses the existing simulator (bb84_core.Alice / Bob and
bb84_noise.QuantumChannel) but batches all single-qubit circuits into a
few large Aer jobs instead of one job per qubit (~100x speedup, same
noise model object, same circuits).

University of Ruhuna - Dept. of Computer Engineering
MIT Licence - see LICENSE
"""

from __future__ import annotations

import math
import time
from dataclasses import dataclass, field
from itertools import combinations
from typing import Dict, List, Optional, Tuple

import numpy as np

from bb84_core import Alice, Bob
from bb84_noise import QuantumChannel, NoiseModelType


# ──────────────────────────────────────────────────────────────────────
# BATCHED SIFTED-KEY GENERATION (wraps the existing simulator classes)
# ──────────────────────────────────────────────────────────────────────

@dataclass
class SiftedPool:
    """A pool of sifted key bits generated by the BB84 simulator."""
    alice_bits: np.ndarray          # uint8, sifted
    bob_bits: np.ndarray            # uint8, sifted
    depolar_prob: float
    n_transmitted: int
    alice_bases: np.ndarray         # bases at the sifted positions
    bit_values: np.ndarray          # Alice's bit at sifted positions (= alice_bits)

    @property
    def n_sifted(self) -> int:
        return len(self.alice_bits)

    @property
    def true_qber(self) -> float:
        """Ground-truth error rate over the whole pool (simulation-only knowledge)."""
        return float(np.mean(self.alice_bits != self.bob_bits))

    def estimated_qber(self, sample_fraction: float = 0.10, seed: int = 0) -> Tuple[float, np.ndarray]:
        """
        Protocol-level QBER estimate from a random sacrificial sample.

        Returns (estimate, mask of remaining usable indices). The sampled
        bits are disclosed and must not be reused as key material.
        """
        rng = np.random.default_rng(seed)
        n = self.n_sifted
        k = max(1, int(n * sample_fraction))
        idx = rng.choice(n, size=k, replace=False)
        est = float(np.mean(self.alice_bits[idx] != self.bob_bits[idx]))
        mask = np.ones(n, dtype=bool)
        mask[idx] = False
        return est, mask

    def estimated_qber_by_basis(
        self, sample_fraction: float = 0.10, seed: int = 0,
    ) -> Tuple[float, Dict[int, float], np.ndarray]:
        """
        Like estimated_qber, but additionally estimates the error rate
        separately for the two (public) measurement bases from the SAME
        sacrificial sample - no extra key material is consumed.

        Returns (overall_estimate, {basis: estimate}, usable-index mask).
        """
        rng = np.random.default_rng(seed)
        n = self.n_sifted
        k = max(1, int(n * sample_fraction))
        idx = rng.choice(n, size=k, replace=False)
        errs = self.alice_bits[idx] != self.bob_bits[idx]
        est = float(np.mean(errs))
        by_basis = {}
        for basis in (0, 1):
            sel = self.alice_bases[idx] == basis
            by_basis[basis] = float(np.mean(errs[sel])) if sel.any() else est
        mask = np.ones(n, dtype=bool)
        mask[idx] = False
        return est, by_basis, mask


def generate_sifted_pool(
    n_sifted_target: int,
    depolar_prob: float = 0.0,
    seed: int = 42,
    batch_size: int = 8000,
    channel_kwargs: Optional[dict] = None,
) -> SiftedPool:
    """
    Generate at least ``n_sifted_target`` sifted key bits with the existing
    BB84 simulator classes, batching Aer execution.

    Uses bb84_core.Alice / Bob for bit & basis generation and circuit
    construction (identical semantics to bb84_runner) and the
    QuantumChannel's own AerSimulator (identical noise model), but submits
    circuits in large batches rather than one job per qubit.

    ``channel_kwargs``: optional full QuantumChannel constructor kwargs
    (e.g. noise_model / t1_ns / t2_ns / gate_time_ns) for non-depolarising
    channels; when given, ``depolar_prob`` is ignored.
    """
    # ~50 % of qubits survive sifting; 2.2x head-room then trim.
    n_qubits = int(n_sifted_target * 2.2) + 64

    alice = Alice(n_qubits, seed=seed)
    bob = Bob(n_qubits, seed=seed)
    if channel_kwargs is not None:
        channel = QuantumChannel(**channel_kwargs)
    else:
        channel = QuantumChannel(
            noise_model=NoiseModelType.DEPOLARIZING if depolar_prob > 0 else NoiseModelType.IDEAL,
            depolar_prob=depolar_prob,
        )
    sim = channel._simulator

    # Build every measured circuit exactly as Bob.measure() does.
    circuits = []
    for i in range(n_qubits):
        qc = alice.prepare_qubit(i)
        if bob.bases[i] == 1:
            qc.h(0)
        qc.measure(0, 0)
        circuits.append(qc)

    measured = np.empty(n_qubits, dtype=np.uint8)
    for start in range(0, n_qubits, batch_size):
        chunk = circuits[start:start + batch_size]
        job = sim.run(chunk, shots=1, seed_simulator=(seed * 7919 + start) % (2**31))
        result = job.result()
        for j in range(len(chunk)):
            counts = result.get_counts(j)
            measured[start + j] = int(list(counts.keys())[0])

    a_bases = np.array(alice.bases)
    b_bases = np.array(bob.bases)
    match = a_bases == b_bases

    a_sift = np.array(alice.bits, dtype=np.uint8)[match]
    b_sift = measured[match]
    bases_sift = a_bases[match]

    if len(a_sift) < n_sifted_target:
        raise RuntimeError(
            f"Sifting shortfall: got {len(a_sift)}, wanted {n_sifted_target}. "
            f"Increase head-room factor."
        )

    return SiftedPool(
        alice_bits=a_sift[:n_sifted_target].copy(),
        bob_bits=b_sift[:n_sifted_target].copy(),
        depolar_prob=depolar_prob,
        n_transmitted=n_qubits,
        alice_bases=bases_sift[:n_sifted_target].copy(),
        bit_values=a_sift[:n_sifted_target].copy(),
    )


# ──────────────────────────────────────────────────────────────────────
# SHANNON HELPERS & RATE ADAPTATION
# ──────────────────────────────────────────────────────────────────────

def h2(p: float) -> float:
    """Binary entropy in bits."""
    if p <= 0.0 or p >= 1.0:
        return 0.0
    return -p * math.log2(p) - (1 - p) * math.log2(1 - p)


def shannon_leak_limit(n: int, p: float) -> float:
    """Minimum syndrome bits for reliable reconciliation: n * h2(p)."""
    return n * h2(p)


def efficiency_margin(n: int) -> float:
    """
    Rate-adaptation safety factor f(n): target leakage = f * n * h2(p).

    Short blocks need a larger margin because both finite-length coding
    losses and QBER-estimate variance grow as n shrinks. Values are a
    transparent, fixed rule (NOT tuned per-cell, to avoid overfitting
    the comparison).
    """
    if n <= 96:
        return 2.2
    if n <= 256:
        return 1.7
    if n <= 1024:
        return 1.40
    return 1.25


def choose_syndrome_length(n: int, p_est: float, available_rates: List[float]) -> Tuple[int, float]:
    """
    Rate adaptation: pick the smallest available syndrome rate m/n that
    is >= f(n) * h2(p_est).  Returns (m, rate).  Falls back to the
    largest available rate if none suffices (flagged by rate check in
    the caller).
    """
    target = efficiency_margin(n) * h2(max(p_est, 1e-4))
    for r in sorted(available_rates):
        if r >= target:
            return int(round(r * n)), r
    r = max(available_rates)
    return int(round(r * n)), r


# ──────────────────────────────────────────────────────────────────────
# LDPC: code construction (pyldpc) + syndrome-target belief propagation
# ──────────────────────────────────────────────────────────────────────

# (d_v, d_c) pairs for regular Gallager codes; syndrome rate m/n = d_v/d_c.
# d_v >= 3 throughout: d_v = 2 "cycle" codes have very poor minimum
# distance and fail BP decoding badly (verified empirically here).
# Each entry is only usable for block lengths n divisible by d_c.
_LDPC_LADDER: List[Tuple[int, int]] = [
    (3, 20),  # 0.15
    (3, 16),  # 0.1875
    (4, 20),  # 0.20
    (5, 20),  # 0.25
    (3, 10),  # 0.30
    (3, 8),   # 0.375
    (4, 10),  # 0.40
    (4, 8),   # 0.50
    (3, 5),   # 0.60
    (5, 8),   # 0.625
    (7, 10),  # 0.70
    (3, 4),   # 0.75
    (7, 8),   # 0.875
]


class LDPCReconciler:
    """
    Rate-adaptive LDPC syndrome reconciliation.

    Holds a ladder of regular LDPC parity-check matrices for one block
    length n and decodes with syndrome-target sum-product BP.

    Rate adaptation uses *measured* per-code thresholds when available
    (see ``calibrate``): BP thresholds differ substantially between
    (d_v, d_c) families, so a generic entropy-margin rule mis-picks codes
    near their threshold. Calibration is done once per block length on
    synthetic BSC data (disjoint seeds from evaluation) - this mirrors how
    deployed QKD systems characterise their code library offline.
    """

    def __init__(self, n: int, seed: int = 0):
        # parity_check_matrix builds H alone; make_ldpc would additionally
        # run an O(n^3) Gaussian elimination for the generator matrix G,
        # which syndrome reconciliation never uses.
        from pyldpc.code import parity_check_matrix

        self.n = n
        self.codes: Dict[float, np.ndarray] = {}
        for d_v, d_c in _LDPC_LADDER:
            if n % d_c != 0:
                continue
            H = parity_check_matrix(n, d_v, d_c, seed=seed)
            H = np.asarray(H.todense() if hasattr(H, "todense") else H, dtype=np.uint8)
            rate = H.shape[0] / n
            self.codes[round(rate, 4)] = H

        if not self.codes:
            raise ValueError(f"No ladder entry divides n={n}; adjust block length.")

    @property
    def available_rates(self) -> List[float]:
        return sorted(self.codes.keys())

    def calibrate(
        self,
        trials: int = 12,
        seed: int = 777_000,
        max_iter: int = 60,
        verbose: bool = False,
    ) -> Dict[float, List[Tuple[float, float]]]:
        """
        Measure each ladder code's frame-error-rate curve FER(p) on
        synthetic BSC blocks, at 6 crossover probabilities spanning
        40-100 % of the code's Shannon limit (h2(p*) = m/n).

        Stored in ``self.fer_curves`` and used by reconcile() to pick the
        rate that maximises expected net key. Calibration seeds are
        disjoint from evaluation seeds, so this is offline code-library
        characterisation, not per-cell tuning.
        """
        from scipy.optimize import brentq

        self.fer_curves: Dict[float, List[Tuple[float, float]]] = {}
        rng = np.random.default_rng(seed)
        for rate in self.available_rates:
            H = self.codes[rate]
            m = H.shape[0]
            p_shannon = brentq(lambda q: h2(q) - m / self.n, 1e-6, 0.499)
            curve = []
            for frac in (0.40, 0.55, 0.70, 0.80, 0.90, 1.00):
                p = p_shannon * frac
                fails = 0
                for t in range(trials):
                    e = (rng.random(self.n) < p).astype(np.uint8)
                    s = ((H @ e) % 2).astype(np.uint8)
                    e_hat, conv, _ = _bp_syndrome_decode(H, s, p, max_iter)
                    if not (conv and np.array_equal(e_hat, e)):
                        fails += 1
                curve.append((p, fails / trials))
                if fails == trials:
                    break  # FER is monotone in p; no point going higher
            self.fer_curves[rate] = curve
            if verbose:
                pts = "  ".join(f"{p:.3f}:{f:.2f}" for p, f in curve)
                print(f"  rate {rate:.4f} (p*={p_shannon:.3f}):  {pts}")
        return self.fer_curves

    def _fer_at(self, rate: float, p: float) -> float:
        """Interpolate the calibrated FER curve at crossover probability p."""
        curve = self.fer_curves[rate]
        ps = [c[0] for c in curve]
        fs = [c[1] for c in curve]
        if p <= ps[0]:
            return fs[0]
        if p >= ps[-1]:
            # Beyond the last measured point (>= Shannon limit if the curve
            # completed, or already at FER=1): assume failure.
            return 1.0 if fs[-1] > 0.99 or p > ps[-1] * 1.02 else fs[-1]
        return float(np.interp(p, ps, fs))

    def _pick_rate(self, p_est: float) -> float:
        """Code maximising expected net key (1 - FER(p_est)) * (n - m) / n."""
        if getattr(self, "fer_curves", None):
            best_rate, best_net = None, -1.0
            for rate in self.available_rates:
                m = self.codes[rate].shape[0]
                net = (1.0 - self._fer_at(rate, p_est)) * (self.n - m) / self.n
                if net > best_net:
                    best_rate, best_net = rate, net
            return best_rate
        _, rate = choose_syndrome_length(self.n, p_est, self.available_rates)
        return rate

    def reconcile(
        self,
        alice_block: np.ndarray,
        bob_block: np.ndarray,
        p_est: float,
        max_iter: int = 120,
        p_vec: Optional[np.ndarray] = None,
        rate_p: Optional[float] = None,
        force_rate: Optional[float] = None,
    ) -> "ReconcileResult":
        """
        Run the full syndrome protocol on one block. See module docstring.

        ``p_vec``     : optional per-position crossover priors for BP
                        (basis-aware decoding); default = uniform p_est.
        ``rate_p``    : optional scalar to drive rate selection with (e.g.
                        an effective entropy-matched p); default = p_est.
        ``force_rate``: bypass rate adaptation entirely and use this ladder
                        rate (controlled experiments only).
        """
        n = self.n
        if force_rate is not None:
            rate = force_rate
        else:
            rate = self._pick_rate(p_est if rate_p is None else rate_p)
        H = self.codes[rate]
        m = H.shape[0]  # exact row count of the chosen code

        t0 = time.perf_counter()
        s_a = (H @ alice_block) % 2          # Alice publishes this
        s_b = (H @ bob_block) % 2
        s_delta = (s_a ^ s_b).astype(np.uint8)  # = H @ e (mod 2)

        e_hat, converged, iters = _bp_syndrome_decode(
            H, s_delta, p_est if p_vec is None else p_vec, max_iter)
        dt = time.perf_counter() - t0

        corrected = bob_block ^ e_hat
        return ReconcileResult(
            method="LDPC",
            n=n,
            leaked_bits=m,
            syndrome_rate=m / n,
            claimed_success=converged,
            actually_correct=bool(np.array_equal(corrected, alice_block)),
            time_s=dt,
            work_units=iters,
        )


def _bp_syndrome_decode(
    H: np.ndarray,
    syndrome: np.ndarray,
    p,
    max_iter: int = 120,
) -> Tuple[np.ndarray, bool, int]:
    """
    Sum-product BP for the syndrome decoding problem  H e = s (mod 2),
    error prior P(e_i = 1) = p  (BSC crossover probability).

    ``p`` may be a scalar (uniform BSC, study-1 behaviour) or a length-n
    vector of per-position crossover probabilities (basis-aware priors).

    Standard tanh-rule message passing on the Tanner graph, with the check
    sign flipped for rows whose target syndrome bit is 1.

    Returns (e_hat, converged, iterations_used).
    """
    m, n = H.shape
    rows, cols = np.nonzero(H)
    n_edges = len(rows)

    p_arr = np.clip(np.broadcast_to(np.asarray(p, dtype=float), n), 1e-6, 0.499)
    llr_prior = np.log((1 - p_arr) / p_arr)    # positive: e_i = 0 favoured
    sign_s = np.where(syndrome[rows] == 1, -1.0, 1.0)

    # Messages live on edges. v2c: variable -> check, c2v: check -> variable.
    v2c = llr_prior[cols].copy()
    c2v = np.zeros(n_edges)

    for it in range(1, max_iter + 1):
        # Check update:  c2v_e = sign_flip * 2 atanh( prod_{e' != e} tanh(v2c_e'/2) )
        t = np.tanh(np.clip(v2c / 2.0, -19.0, 19.0))
        t = np.where(np.abs(t) < 1e-12, 1e-12 * np.sign(t + 1e-30), t)
        prod_all = np.ones(m)
        np.multiply.at(prod_all, rows, t)
        ext = prod_all[rows] / t
        ext = np.clip(ext, -0.999999999, 0.999999999)
        c2v = sign_s * 2.0 * np.arctanh(ext)

        # Variable update and posterior
        sum_all = np.zeros(n)
        np.add.at(sum_all, cols, c2v)
        posterior = llr_prior + sum_all
        v2c = posterior[cols] - c2v

        e_hat = (posterior < 0).astype(np.uint8)
        if np.array_equal((H @ e_hat) % 2, syndrome):
            return e_hat, True, it

    return e_hat, False, max_iter


# ──────────────────────────────────────────────────────────────────────
# GRAND: dense random code + weight-ordered noise guessing
# ──────────────────────────────────────────────────────────────────────

class GRANDReconciler:
    """
    Syndrome-based GRAND reconciliation over a dense random linear code.

    Alice publishes s_A = H x; Bob forms s_delta = H e and guesses error
    patterns in increasing Hamming-weight order (maximum-likelihood order
    for a BSC with p < 0.5), accepting the first pattern e with
    H e = s_delta.  Complexity is bounded by ``max_guesses``; hitting the
    bound = abandonment (reported as failure).

    Columns of H are bit-packed into Python ints so each candidate costs
    ~1 XOR; a prefix-XOR recursion over combinations amortises the work.
    """

    def __init__(self, n: int, seed: int = 0):
        self.n = n
        self._rng = np.random.default_rng(seed)
        self._col_cache: Dict[int, List[int]] = {}   # m -> packed columns
        self._H_cache: Dict[int, np.ndarray] = {}

    def _get_code(self, m: int) -> Tuple[List[int], np.ndarray]:
        if m not in self._col_cache:
            H = self._rng.integers(0, 2, size=(m, self.n), dtype=np.uint8)
            cols = [int("".join(map(str, H[:, j])), 2) for j in range(self.n)]
            self._col_cache[m] = cols
            self._H_cache[m] = H
        return self._col_cache[m], self._H_cache[m]

    def reconcile(
        self,
        alice_block: np.ndarray,
        bob_block: np.ndarray,
        p_est: float,
        max_guesses: int = 2_000_000,
        w_max: Optional[int] = None,
        basis: Optional[np.ndarray] = None,
        p_by_class: Optional[Dict[int, float]] = None,
    ) -> "ReconcileResult":
        """
        Weight-ordered GRAND (default), or - when ``basis`` and
        ``p_by_class`` are given - two-class maximum-likelihood-ordered
        GRAND that exploits the public per-basis error rates: patterns are
        enumerated in exact likelihood order for the mixture-BSC channel,
        and the syndrome length shrinks to the mixture entropy
        m = ceil(n0 h2(p0) + n1 h2(p1)) + 16 (<= the uniform rule, by
        concavity of h2).
        """
        if basis is not None and p_by_class is not None:
            return self._reconcile_two_class(alice_block, bob_block, basis,
                                             p_by_class, max_guesses)
        n = self.n
        # GRAND rate adaptation: with ML-ordered guessing, the true error
        # pattern always matches its own syndrome; failure modes are
        # (a) abandonment (budget) and (b) a wrong pattern colliding with
        # the target syndrome *earlier* in the guessing order. Candidates
        # preceding the true pattern number ~2^(n h2(p)), each colliding
        # with probability 2^-m for a random code, so
        #     m = ceil(n h2(p_est)) + safety_bits
        # keeps undetected errors at ~2^-safety_bits. This is within a
        # constant of the Slepian-Wolf optimum at ANY block length - the
        # structural leakage advantage GRAND holds at short n.
        safety_bits = 16
        m = max(4, min(n, int(math.ceil(n * h2(max(p_est, 1e-4)))) + safety_bits))

        cols, H = self._get_code(m)

        t0 = time.perf_counter()
        s_a = (H @ alice_block) % 2
        s_b = (H @ bob_block) % 2
        s_delta = s_a ^ s_b
        target_int = int("".join(map(str, s_delta)), 2)

        if w_max is None:
            mu = n * max(p_est, 1e-3)
            w_max = int(math.ceil(mu + 5.0 * math.sqrt(mu * (1 - max(p_est, 1e-3))))) + 1
            w_max = min(w_max, n)

        e_pos, guesses = _grand_search(cols, n, target_int, w_max, max_guesses)
        dt = time.perf_counter() - t0

        found = e_pos is not None
        e_hat = np.zeros(n, dtype=np.uint8)
        if found:
            e_hat[list(e_pos)] = 1

        corrected = bob_block ^ e_hat
        return ReconcileResult(
            method="GRAND",
            n=n,
            leaked_bits=m,
            syndrome_rate=m / n,
            claimed_success=found,
            actually_correct=bool(np.array_equal(corrected, alice_block)),
            time_s=dt,
            work_units=guesses,
        )


    def _reconcile_two_class(
        self,
        alice_block: np.ndarray,
        bob_block: np.ndarray,
        basis: np.ndarray,
        p_by_class: Dict[int, float],
        max_guesses: int,
    ) -> "ReconcileResult":
        n = self.n
        idx0 = [j for j in range(n) if basis[j] == 0]
        idx1 = [j for j in range(n) if basis[j] == 1]
        p0 = min(max(p_by_class[0], 1e-4), 0.499)
        p1 = min(max(p_by_class[1], 1e-4), 0.499)

        # Mixture-entropy leakage rule (<= uniform rule by h2 concavity)
        m = int(math.ceil(len(idx0) * h2(p0) + len(idx1) * h2(p1))) + 16
        m = max(4, min(n, m))
        cols, H = self._get_code(m)

        t0 = time.perf_counter()
        s_a = (H @ alice_block) % 2
        s_b = (H @ bob_block) % 2
        s_delta = s_a ^ s_b
        target_int = int("".join(map(str, s_delta)), 2)

        def wcap(k, p):
            mu = k * max(p, 1e-3)
            return min(k, int(math.ceil(mu + 5.0 * math.sqrt(mu * (1 - max(p, 1e-3))))) + 1)

        e_pos, guesses = _grand_search_two_class(
            cols, idx0, idx1,
            math.log((1 - p0) / p0), math.log((1 - p1) / p1),
            target_int, wcap(len(idx0), p0), wcap(len(idx1), p1), max_guesses)
        dt = time.perf_counter() - t0

        found = e_pos is not None
        e_hat = np.zeros(n, dtype=np.uint8)
        if found:
            e_hat[list(e_pos)] = 1
        corrected = bob_block ^ e_hat
        return ReconcileResult(
            method="GRAND",
            n=n,
            leaked_bits=m,
            syndrome_rate=m / n,
            claimed_success=found,
            actually_correct=bool(np.array_equal(corrected, alice_block)),
            time_s=dt,
            work_units=guesses,
        )


def _combo_xor_iter(cols: List[int], idx: List[int], w: int):
    """
    Yield (positions_tuple, xor_of_columns) over all size-w combinations of
    ``idx``, with a prefix-XOR stack so successive combinations cost ~1 XOR.
    """
    if w == 0:
        yield (), 0
        return
    k = len(idx)
    if w > k:
        return
    sel = list(range(w))
    prefix = [0] * (w + 1)
    for i in range(w):
        prefix[i + 1] = prefix[i] ^ cols[idx[sel[i]]]
    while True:
        yield tuple(idx[s] for s in sel), prefix[w]
        j = w - 1
        while j >= 0 and sel[j] == k - w + j:
            j -= 1
        if j < 0:
            return
        sel[j] += 1
        prefix[j + 1] = prefix[j] ^ cols[idx[sel[j]]]
        for t in range(j + 1, w):
            sel[t] = sel[t - 1] + 1
            prefix[t + 1] = prefix[t] ^ cols[idx[sel[t]]]


def _grand_search_two_class(
    cols: List[int],
    idx0: List[int],
    idx1: List[int],
    c0: float,
    c1: float,
    target: int,
    w0_max: int,
    w1_max: int,
    max_guesses: int,
) -> Tuple[Optional[Tuple[int, ...]], int]:
    """
    Exact ML-ordered GRAND for a two-class mixture BSC: every pattern with
    w0 errors in class 0 and w1 in class 1 has log-likelihood penalty
    w0*c0 + w1*c1 (c = log((1-p)/p) > 0), so enumerating (w0, w1) pairs by
    ascending penalty and exhausting each pair is maximum-likelihood order.
    """
    pairs = sorted(
        ((w0, w1) for w0 in range(min(w0_max, len(idx0)) + 1)
         for w1 in range(min(w1_max, len(idx1)) + 1)),
        key=lambda t: t[0] * c0 + t[1] * c1)

    guesses = 0
    for w0, w1 in pairs:
        for pos0, x0 in _combo_xor_iter(cols, idx0, w0):
            for pos1, x1 in _combo_xor_iter(cols, idx1, w1):
                guesses += 1
                if guesses > max_guesses:
                    return None, guesses - 1
                if x0 ^ x1 == target:
                    return pos0 + pos1, guesses
    return None, guesses


def _grand_search(
    cols: List[int],
    n: int,
    target: int,
    w_max: int,
    max_guesses: int,
) -> Tuple[Optional[Tuple[int, ...]], int]:
    """
    Weight-ordered enumeration of error patterns.

    Iterative prefix-XOR over lexicographic combinations: consecutive
    combinations share long prefixes, so most candidates cost one XOR.
    Returns (positions_of_first_match or None, guesses_used).
    """
    guesses = 0

    if target == 0:
        return (), 1  # weight-0 pattern matches: no errors

    for w in range(1, w_max + 1):
        # Iterative combination enumeration with a prefix-XOR stack.
        idx = list(range(w))
        prefix = [0] * (w + 1)          # prefix[k] = XOR of cols[idx[0..k-1]]
        for k in range(w):
            prefix[k + 1] = prefix[k] ^ cols[idx[k]]

        while True:
            guesses += 1
            if guesses > max_guesses:
                return None, guesses - 1
            if prefix[w] == target:
                return tuple(idx), guesses

            # Advance to next combination (lexicographic), reusing prefixes.
            j = w - 1
            while j >= 0 and idx[j] == n - w + j:
                j -= 1
            if j < 0:
                break
            idx[j] += 1
            prefix[j + 1] = prefix[j] ^ cols[idx[j]]
            for k in range(j + 1, w):
                idx[k] = idx[k - 1] + 1
                prefix[k + 1] = prefix[k] ^ cols[idx[k]]

    return None, guesses


# ──────────────────────────────────────────────────────────────────────
# RESULT RECORD
# ──────────────────────────────────────────────────────────────────────

@dataclass
class ReconcileResult:
    """Outcome of one reconciliation attempt on one block."""
    method: str
    n: int
    leaked_bits: int
    syndrome_rate: float
    claimed_success: bool       # decoder itself thinks it converged/found e
    actually_correct: bool      # ground truth: corrected key == Alice's key
    time_s: float
    work_units: int             # BP iterations or GRAND guesses

    @property
    def undetected_error(self) -> bool:
        """Decoder claimed success but the key is wrong (would need hash check)."""
        return self.claimed_success and not self.actually_correct

    @property
    def net_key_fraction(self) -> float:
        """Fraction of the block surviving as corrected key: (n - m)/n if correct, else 0."""
        if not self.actually_correct:
            return 0.0
        return max(0.0, (self.n - self.leaked_bits) / self.n)


def result_row(r: ReconcileResult, qber_label: str, p_true: float, p_est: float, trial: int) -> dict:
    """Flatten a ReconcileResult into a DataFrame-friendly dict."""
    return {
        "method": r.method,
        "n": r.n,
        "qber_label": qber_label,
        "p_true": p_true,
        "p_est": p_est,
        "trial": trial,
        "leaked_bits": r.leaked_bits,
        "syndrome_rate": r.syndrome_rate,
        "claimed_success": r.claimed_success,
        "correct": r.actually_correct,
        "undetected_error": r.undetected_error,
        "net_key_fraction": r.net_key_fraction,
        "time_s": r.time_s,
        "work_units": r.work_units,
    }
